server:
 port: 8081
 seesion-timeout: 30
 tomcat.max-threads: 0
 tomcat.uri-encoding: UTF-8
 
spring:
 thymeleaf:
  prefix: classpath:/static/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false
 datasource:
  url: jdbc:mysql://localhost:3306/harmonica
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: yangyang
  initial-size: 10
  max-active: 20
  max-idle: 8
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: update
   naming:
    physical-strategy:
     org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    